### PR TITLE
fix start Minimized feature issue on linux, Closes  #1016

### LINKED ISSUE #1016: 'Start minimized' does not work on linux
**Describe the bug**
See title

**To Reproduce**
1. Go to 'Settings', 'Application'
2. Enable 'Auto start', 'Auto connect', 'Start minimized'
3. Reboot device

**Expected behavior**
I expect the application to be minimized to tray

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04, GNOME with **Xorg** (not wayland)

**Server (please complete the following information):**
 - OS: Ubuntu 24.04

### PR DESCRIPTION
**Pull request by ShehabAhmed-Gui**
As the issue #1016 says: the "start minimized" option in amnezia settings wasn't working on Linux, I fixed it.

### CODE REVIEW

File: client/ui/controllers/pageController.cpp [hunk 1]
```diff
@@ -135,6 +135,8 @@ void PageController::showOnStartup()
         emit hideMainWindow();
 #elif defined Q_OS_MACX
         setDockIconVisible(false);
+#elif defined Q_OS_LINUX
```
Comment (Nethius) [inline client/ui/controllers/pageController.cpp]:
```
#if defined(Q_OS_WIN) || defined(Q_OS_LINUX)
        emit hideMainWindow();
#elif defined Q_OS_MACX
        setDockIconVisible(false);
#endif
```

**Review by Nethius — CHANGES_REQUESTED** [review]

**Review by Nethius — APPROVED** [review]
